/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as deterministicErc20FactorySol from './DeterministicERC20Factory.sol';
export { SimpleFactory__factory } from './SimpleFactory__factory';
export { SimpleToken__factory } from './SimpleToken__factory';
export { USDCOV__factory } from './USDCOV__factory';
