/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as deterministicErc20FactorySol from './DeterministicERC20Factory.sol';
export type { deterministicErc20FactorySol };
export type { SimpleFactory } from './SimpleFactory';
export type { SimpleToken } from './SimpleToken';
export type { USDCOV } from './USDCOV';
